spring:
  datasource:
    url: jdbc:sqlite:soapdesk.db
    driver-class-name: org.sqlite.JDBC
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.community.dialect.SQLiteDialect
logging:
  level:
    root: INFO
    com.enterprise.soapdesk: DEBUG
